POPULAR_MOVIES = [
    "The Shawshank Redemption",
    "The Godfather",
    "The Dark Knight",
    "Pulp Fiction",
    "Forrest Gump",
    "Inception",
    "Fight Club",
    "The Matrix",
    "Goodfellas",
    "The Silence of the Lambs",
    "The Lord of the Rings: The Return of the King",
    "Star Wars: Episode V - The Empire Strikes Back",
    "The Lord of the Rings: The Fellowship of the Ring",
    "Interstellar",
    "The Usual Suspects",
    "The Green Mile",
    "The Departed",
    "The Prestige",
    "The Lion King",
    "Gladiator",
    "The Shining",
    "The Avengers",
    "The Dark Knight Rises",
    "The Lord of the Rings: The Two Towers",
    "The Social Network"
]